### ISSUE TITLE
(Apparently) inconsistent version requirements of Microsoft.Testing.Extensions.VSTestBridge

### ISSUE THREAD

**Issue by lennartb-** [nunit/nunit3-vs-adapter#1292]
Hi,

I'm currently troubleshooting an issue we have since updating to NUnit3TestAdapter to 5.1.0. We're getting the build error:

```
Assembly 'NUnit3.TestAdapter' with identity 'NUnit3.TestAdapter, Version=5.1.0.0, Culture=neutral, PublicKeyToken=4cb40d35494691ac' uses 'Microsoft.Testing.Platform, Version=1.8.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'Microsoft.Testing.Platform' with identity 'Microsoft.Testing.Platform, Version=1.7.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

Which seemed strange to me, because NuGet says that the package requires version >=1.7.3, so where does 1.8.1.0 come from?

It seems that in [nuget/NUnit3TestAdapter.nuspec](https://github.com/nunit/nunit3-vs-adapter/blob/9893f2cbdb878ba474f42f8ff63be6ec69549fd7/nuget/NUnit3TestAdapter.nuspec#L30), the requirements for NuGet are set to 1.7.3, while in [Directory.Packages.props](https://github.com/nunit/nunit3-vs-adapter/blob/9893f2cbdb878ba474f42f8ff63be6ec69549fd7/Directory.Packages.props#L20) it's 1.8.1.

I can fix this locally by just explicitly installing 1.8.0, but I wondered whether the difference in the package is okay and/or intended.

**Comment by manfred-brands** [comment]
@OsirisTerje I have copied and adapted the `NuspecDependenciesTests` test from nunit where we had the same problem.
It will likely need some tweaking to suite this project.

It did find the reported inconsistency:
```
Package Microsoft.Testing.Extensions.VSTestBridge in .csproj should have version '1.8.1' in .nuspec
Assert.That(nuspecVersion, Is.EqualTo(pair.Version))
  String lengths are both 5. Strings differ at index 2.
  Expected: "1.8.1"
  But was:  "1.7.3"
  -------------^
```

**Comment by moh-hassan** [comment]
I update my test project for the package `NUnit3TestAdapter`  from v 5.0.0 to v 5.1.0 , then get compilation error:
>Assembly 'NUnit3.TestAdapter' with identity 'NUnit3.TestAdapter, Version=5.1.0.0, Culture=neutral, PublicKeyToken=4cb40d35494691ac' uses 'Microsoft.Testing.Platform, Version=1.8.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'Microsoft.Testing.Platform' with identity 'Microsoft.Testing.Platform, Version=1.7.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

I don't reference  the package `Microsoft.Testing.Platform`

If i add the package  `Microsoft.Testing.Platform` , I get many runtime errors require  other package: :`Microsoft.Testing.Extensions.VSTestBridge` v 1.8.1.0

i check the [dependency](https://www.nuget.org/packages/NUnit3TestAdapter#dependencies-body-tab) in nuget Gallary and find different dependencies.

I had to return back to v 5.0.0

**Note:**  The issue can be reproduced  by modifying the sample project in [issue1152](https://github.com/nunit/nunit3-vs-adapter.issues/blob/master/Issue1152/2-nunit-runner-dotnet-test/nunit-runner-dotnet-test.csproj) and modify the version to 5.1.0.

**Workaround solution**
Add reference to the next packages

```xml
<PackageReference Include="Microsoft.Testing.Platform" Version="1.8.1" />
<PackageReference Include="Microsoft.Testing.Extensions.VSTestBridge" Version="1.8.1" />

```
It works fine in net10,net8 in MTP mode in both vs2022 TE and `dotnet test`

**Comment by OsirisTerje** [comment]
You can also try the latest Myget package, that one should have the correct dependencies.

**Comment by moh-hassan** [comment]
@OsirisTerje , thanks for reply.
The last package in [myget](https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/5.1.0) is v5.1.0  on date "Sat, 16 Aug 2025 19:53:43 GMT" which has the same bug.
Kindly, can you upload to myget  a maintenance package  e.g. 5.1.1 so I can try it.
it may need adjustment of allowed version in nuspec file.

**Comment by moh-hassan** [comment]
i modified the [nuspec](https://github.com/nunit/nunit3-vs-adapter/blob/main/nuget/NUnit3TestAdapter.nuspec) file as:
```
<dependencies>
      <group targetFramework="net462">
        <dependency id="Microsoft.Testing.Extensions.VSTestBridge" version="1.8.1" />
        <dependency id="Microsoft.Testing.Platform.MSBuild" version="1.8.1" />
      </group>
      <group targetFramework="netcoreapp3.1">
        <dependency id="Microsoft.Testing.Extensions.VSTestBridge" version="1.8.1" />
        <dependency id="Microsoft.Testing.Platform.MSBuild" version="1.8.1" />
      </group>
    </dependencies>
```

Then generate  the package as 5.1.2. The `nuspec` file inside the package is correct and dependencies are 5.1.2 .
I used the package instead of 51.0  in my project
It works fine in net10,net8 in MTP mode in both vs2022 TE and dotnet test
The attached working package 5.1.2  [NUnit3TestAdapter.5.1.2.zip](https://github.com/user-attachments/files/21970329/NUnit3TestAdapter.5.1.2.zip)

**Comment by Youssef1313** [comment]
@OsirisTerje Any plans to publish 5.1.x bugfix for this?
I don't get why it is set to 5.2 when it's a bugfix?

**Comment by OsirisTerje** [comment]
@Youssef1313 If it doesn't seem to be critical and blocking and thus requiring a hotfix release, I just add them to the next upcoming minor release.  

@lennartb- said 

> I can fix this locally by just explicitly installing 1.8.1,

**Comment by moh-hassan** [comment]
Using net10 RC1 sdk + MTP with the package NUnit3TestAdapter  v5.0.0  raise error:
```
System.Collections.Generic.KeyNotFoundException: The given key '8' was not present in the dictionary.

```
And v5.1.0 has a bug.
I tried [myget package v5.1.1-alpha.1](https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter)  and it is working fine in net10 +mtp.
@OsirisTerje , kindly, can you publish it in `nuget `

**Comment by Youssef1313** [comment]
@moh-hassan That sounds like potentially a different issue?
Do you have a full stack trace please? Does it reproduce with MSTest or is it NUnit only?

**Comment by moh-hassan** [comment]
@Youssef1313 

<details>
<summary>Stack trace of nunit with MTP in net10 RC1 (dotnet.config in solution folder)</summary>
Build succeeded in 8.7s
Process terminated.
System.Collections.Generic.KeyNotFoundException: The given key '8' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.DotNet.Cli.Commands.Test.TestApplicationsEventHandlers.OnHandshakeReceived(Object sender, HandshakeArgs args)
   at Microsoft.DotNet.Cli.Commands.Test.TestApplication.OnRequest(IRequest request)
   at System.Environment.FailFast(System.Runtime.CompilerServices.StackCrawlMarkHandle, System.String, System.Runtime.CompilerServices.ObjectHandleOnStack, System.String)
   at System.Environment.FailFast(System.Threading.StackCrawlMark ByRef, System.String, System.Exception, System.String)
   at System.Environment.FailFast(System.String)
   at Microsoft.DotNet.Cli.Commands.Test.TestApplication.OnRequest(Microsoft.DotNet.Cli.Commands.Test.IPC.IRequest)
   at Microsoft.DotNet.Cli.Commands.Test.IPC.NamedPipeServer+<InternalLoopAsync>d__22.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.DotNet.Cli.Commands.Test.IPC.NamedPipeServer+<InternalLoopAsync>d__22, dotnet, Version=10.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.DotNet.Cli.Commands.Test.IPC.NamedPipeServer+<InternalLoopAsync>d__22, dotnet, Version=10.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.DotNet.Cli.Commands.Test.IPC.NamedPipeServer+<InternalLoopAsync>d__22, dotnet, Version=10.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
</details>
   
**Note:**  If i run the exe  from bin folder OR  use `dotnet run` from project folder , it run successfully without errors


-------------------------
I tried MsTest project in same environment using the package:

```
<PackageReference Include="MSTest.TestFramework" Version="3.11.0" />
```
When try to run build, error is raised:

<details >
<summary>Exception of Build output of MSTest v 3.11.0 project in net10 RC1 (dotnet.config in solution folder)</summary>
>dotnet build

C:\Users\mohha\source\repos\TestProject7>dotnet build
Restore complete (0.6s)
    info NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  MsTestProject net472 failed with 1 error(s) (0.0s)
    CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point
  MsTestProject net8.0 failed with 1 error(s) (0.2s)
    CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point

Build failed with 2 error(s) in 1.1s

</details>


But it works fine using v4.0.0-preview.25480.4
```
   <PackageReference Include="MSTest" Version="4.0.0-preview.25480.4" />
```   

Demo project: 
[TestProject.zip](https://github.com/user-attachments/files/22712345/TestProject.zip)

**Comment by Youssef1313** [comment]
This is because you are depending on MTP 1.5.3 (coming through NUnit3TestAdapter 5.0.0). You need to use 5.1.0 with the workaround of explicitly adding MTP 1.9.0 to your project.

**Comment by Youssef1313** [comment]
> [@Youssef1313](https://github.com/Youssef1313) If it doesn't seem to be critical and blocking and thus requiring a hotfix release, I just add them to the next upcoming minor release.
> 
> [@lennartb-](https://github.com/lennartb-) said
> 
> > I can fix this locally by just explicitly installing 1.8.1,

It's not completely blocking, but I do think it's worth servicing in a 5.1.x as it's a regression bug with low risk to fix in 5.1.x.

**Comment by OsirisTerje** [comment]
I might get out 5.2 in a few days.

**Comment by Youssef1313** [comment]
In that case, fine to not backport.

**Comment by moh-hassan** [comment]
@Youssef1313 
>This is because you are depending on MTP 1.5.3 (coming through NUnit3TestAdapter 5.0.0). You need to use 5.1.0 with the workaround of explicitly adding MTP 1.9.0 to your project.

You are correct.
I used `NUnit3TestAdapter ' v5.1.0 with the workaround  of referencing MTP v1.9.0 for the following package:
```
	<PackageReference Include="NUnit3TestAdapter" Version="5.1.0" />
                      <!-- to fix the package beak -->
	<PackageReference Include="Microsoft.Testing.Platform.MSBuild" Version="1.9.0" />
	<PackageReference Include="Microsoft.Testing.Extensions.VSTestBridge" Version="1.9.0" />
		
```

Now it works fine in net10 RC1 with MTP mode (dotnet.config is in solution folder)
The package dependency in vs2022 is like:

<img width="289" height="154" alt="Image" src="https://github.com/user-attachments/assets/fac46f19-9e84-4832-b320-fcd4da437aae" />

**Comment by OsirisTerje** [comment]
@moh-hassan @Youssef1313 

5.2.0 released now :-)

**Comment by moh-hassan** [comment]
@OsirisTerje 
>5.2.0 released now

It Works FINE. 👍 

The package dependency:

<img width="293" height="123" alt="Image" src="https://github.com/user-attachments/assets/fddeda17-2c76-40ec-96ab-12d555fb04e1" />

**Comment by OsirisTerje** [comment]
Thanks for checking @moh-hassan !

**Comment by JasonBock** [comment]
@OsirisTerje FWIW I'm seeing this show up in VS 2026 referencing 6.0.1-alpha.6 :(

**Comment by OsirisTerje** [comment]
@JasonBock  Not sure what you mean.  The adapter 6 needs 2.0.2

<img width="533" height="159" alt="Image" src="https://github.com/user-attachments/assets/7706bd6e-9e0d-46b9-a4ba-946eb52d8fe1" />

And it is 2.0.2 in all the correct places.

**Comment by JasonBock** [comment]
Just saying that if I referenced 6.0.1-alpha.6 and I don't have these references:

```xml
<!--<PackageReference Include="Microsoft.Testing.Extensions.VSTestBridge" />
<PackageReference Include="Microsoft.Testing.Platform.MSBuild" />-->
```

And I have this in my project file:

```xml
<PropertyGroup>
	<EnableNUnitRunner>true</EnableNUnitRunner>
	<OutputType>Exe</OutputType>
	<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
</PropertyGroup>
```

I get this error:

```
The type or namespace name 'Testing' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
```

<img width="380" height="117" alt="Image" src="https://github.com/user-attachments/assets/18510a3f-2a51-47b2-b3da-0f5586d86c34" />

**Comment by OsirisTerje** [comment]
@JasonBock That is weird.  

I copied one of your test projects from earlier into the Issue52 repro,  https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue1152  (there are 2 more there from @Youssef1313 way back, but updated), and all works as they should without those extra references. 
The only thing I noted was that the global.json needed to be in the root folder, and didnt work if placed with the csprojs. 

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <RootNamespace>nunit_runner</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <!-- 
      These 2 lines are required as some opt-in to the new platform 
      to minimize disruptancy for end users.
    -->
    <!--<EnableNUnitRunner>true</EnableNUnitRunner>
	<OutputType>Exe</OutputType>-->
  </PropertyGroup>
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableNUnitRunner>true</EnableNUnitRunner>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit.Analyzers" Version="4.11.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" Version="6.0.1-alpha.6" />
  </ItemGroup>
  <Target Name="ShowEnableNUnitRunner" BeforeTargets="Build">
    <Message Text="EnableNUnitRunner is set to: $(EnableNUnitRunner)" Importance="High" />
  </Target>
</Project>

```

PS:  This is with .net 10 sdk/dotnet 10 host.

**Comment by JasonBock** [comment]
FWIW it's happening with a solution that I just set up to go through Advent of Code 2025 - https://github.com/JasonBock/AdventOfCode2025. I just added a `global.json` with the MTP setting in it and that didn't seem to help.

**Comment by OsirisTerje** [comment]
I have also struggled with the global.json.  The guidelines here:  https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test#migrate-to-mtp-mode-of-dotnet-test for migration doesn't state all one need.  I have found the global.json has to be in the same folder as the solution file, if you start your dotnet test there. 

There might be more.....
